### ISSUE TITLE
ValueError: AES key must be either 16, 24, or 32 bytes long

### ISSUE THREAD

**Issue by ghost** [naohaq/miyaguchi-preneel#1]
Problem at Windows 7 Python 2.7 and Debian Stretch Python 2.7

`
python aes-mp.py 

Traceback (most recent call last):
  File "aes-mp.py", line 29, in <module>
    hval = AES_MP128.comp(in_binary)
  File "/home/xxx/Downloads/git/miyaguchi-preneel/AES_MP128.py", line 25, in comp
    result = aes_mp.comp(_IV, text)
  File "/home/xxx/Downloads/git/miyaguchi-preneel/MiyaguchiPreneel.py", line 35, in comp
    out_cur = _comp_step(e, g, out_pre, x_cur)
  File "/home/xxx/Downloads/git/miyaguchi-preneel/MiyaguchiPreneel.py", line 9, in _comp_step
    h_enc = e(h_key, x_cur)
  File "/home/xxx/Downloads/git/miyaguchi-preneel/AES_MP128.py", line 9, in _enc_aes
    enc  = AES.new(k, mode)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long

Same with older version:

python aes-mp.py 

Traceback (most recent call last):
  File "aes-mp.py", line 50, in <module>
    hval = aes_mp.comp(IV, in_binary)
  File "/home/xxx/Downloads/git/miyaguchi-preneel-16e97900709d7322c0aee0410383e8de34079c9f/MiyaguchiPreneel.py", line 35, in comp
    out_cur = _comp_step(e, g, out_pre, x_cur)
  File "/home/xxx/Downloads/git/miyaguchi-preneel-16e97900709d7322c0aee0410383e8de34079c9f/MiyaguchiPreneel.py", line 9, in _comp_step
    h_enc = e(h_key, x_cur)
  File "aes-mp.py", line 12, in enc_aes
    enc  = AES.new(k, mode)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long`

**Comment by naohaq** [comment]
I found that the problem was due to behavior of the function `bytes()` on Python2.7.
In "AES_MP128.py", the initialization vector is generated as following:
```python
_hlen = 128
_IV = bytes(0 for i in range(_hlen//8))
```
On Python3.x, `_IV` becomes the value `b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`, that is 16 bytes in length.
However, on Python2.7, it becomes a string like `'<generator object <genexpr> at 0x7f025a222780>'`. The length of `_IV` is 46 bytes in this case.

**Comment by naohaq** [comment]
Applied workaround using `future`.
Current code seems to work well on my environment.
```console
$ python2 --version
Python 2.7.13
$ python2 aes-mp.py
e732a43c377b26f391f6f0ecb2e66a11
```

**Comment by naohaq** [comment]
May I close this issue?
